name: data-access-service
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip<24.1
  - virtualenv==20.28.1 # https://github.com/python-poetry/poetry/issues/10056#issuecomment-2594269592
  - pip:
      - poetry==2.0.1
