[tool.poetry]
name = "data-access-service"
version = "0.1.0"
description = ""
authors = ["utas-raymondng <manfai.ng@utas.edu.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.14"
python-levenshtein = "~0.25.1"
flask = "^3.0.3"
gunicorn = "^22.0.0"
jsonify = "^0.5"

# Dependency from a GitHub repository
aodn_cloud_optimised = { git = "https://github.com/aodn/aodn_cloud_optimised.git", branch = "main" }
fuzzywuzzy = "^0.18.0"
logging = "^0.4.9.6"
xmltodict = "^0.13.0"
watchdog = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
