aws:
  s3:
    bucket_name:
      subsetting: aodn-cloud-optimized-subset-dev
      portal_data: aodnportal-dev-data
      wave_buoy_backup: aodn-cloud-optimized-wave-buoy-backup-testing
      mooring_backup: aodn-cloud-optimized-wave-buoy-backup-testing
  ses:
    sender_email: no.reply@aodn.org.au
  batch:
    job_queue: generate-csv-data-file
    job_definition: generate-csv-data-file-dev
pmtiles:
  config:
    threads: 12
