aws:
  s3:
    bucket_name:
      csv: havier-example-bucket
  ses:
    sender_email: no.reply@aodn.org.au
  batch:
    job_queue: generate-csv-data-file
    job_definition: generate-csv-data-file-dev
    index_job_definition: scheduled-es-indexing-dev
