csiro:
  datasets:
    - dataset_name: uwy_csiro.parquet
      key_request_url: https://data.csiro.au/dap/api/v2/collections/72626/files/s3
aws:
  s3:
    bucket_name:
      csv: aodn-cloud-optimized-subset-edge
      wave_buoy_backup: datavis-apps-edge-data
      mooring_backup: datavis-apps-edge-data
  ses:
    sender_email: no.reply@aodn.org.au
  batch:
    job_queue: data-access-service-batch-job-queue
    job_definition: data-access-service-batch-job-definition
pmtiles:
  config:
    bucket_name: aodnportal-edge-data
