csiro:
  datasets:
    - dataset_name: uwy_csiro.parquet
      fedora_pid: csiro:72626
aws:
  s3:
    bucket_name:
      subsetting: aodn-cloud-optimized-subset-staging
      portal_data: aodnportal-staging-data
      datavis_data: datavis-apps-staging-data
  ses:
    sender_email: no.reply@aodn.org.au
  batch:
    job_queue: data-access-service-batch-job-queue
    job_definition: data-access-service-batch-job-definition
