aws:
  s3:
    bucket_name:
      csv: aodn-cloud-optimized-subset-prod
  ses:
    sender_email: no.reply@aodn.org.au
  batch:
    job_queue: generate-csv-data-file
    job_definition: generate-csv-data-file
    index_job_definition: scheduled-es-indexing
