aws:
  s3:
    bucket_name:
      subsetting: aodn-cloud-optimized-subset-staging
      portal_data: aodnportal-staging-data
      wave_buoy_backup: datavis-apps-staging-data
      mooring_backup: datavis-apps-staging-data
  ses:
    sender_email: no.reply@aodn.org.au
  batch:
    job_queue: generate-csv-data-file
    job_definition: generate-csv-data-file
