"""In-memory ``Product`` registry, published once at startup by tiler warmup.

A state holder and nothing more. Products are no longer read from disk here —
they are *derived* from the metadata catalogue and the gridded-variable config
(see [[discovery]]), verified against the stores that actually opened (see
[[verification]]), and only then handed to ``publish_products``.

  * The ``PRODUCTS`` dict is the canonical registered-product state. Internal
    consumers (test fixtures, the prewarm race-guard) still touch it directly
    where the dict's identity matters; production callers should go through
    the facades (``get_product``, ``iter_products``, ``iter_product_items``).
  * ``id`` convention: ``{zarr_name}:{variable}``, e.g.
    ``satellite_austemp_heatwave_14day:sst_mosaic`` — the colon separates the
    Zarr store name (from ``source_path``) from the variable it exposes,
    since both may themselves contain underscores. Multi-variable products
    join variables with ``+`` in ``variable`` array order, e.g.
    ``model_sea_level_anomaly_gridded_realtime:ucur+vcur``. ``id`` is never
    parsed at runtime, just used as an opaque lookup key, but the format is a
    compatibility surface: it is generated by ``discovery.product_id`` and
    cached by the frontend.
  * ``GET /products`` is built from ``iter_products()`` (live ``Product``
    instances), so it reflects each product's resolved configuration.
"""

import logging

from data_access_service.tiler.services.product.product import Product

logger = logging.getLogger(__name__)

# Canonical registered-product state. Exposed (rather than wrapped behind a
# class) because the dict identity is load-bearing for test fixtures and for
# the prewarm race-guard ``PRODUCTS.get(p.id) is not p`` check — both rely on
# the same Python object being mutated in place.
PRODUCTS: dict[str, Product] = {}


def get_product(product_id: str) -> Product | None:
    """Return the registered Product for ``product_id``, or None if not registered."""
    return PRODUCTS.get(product_id)


def iter_products() -> list[Product]:
    """Snapshot of every registered Product.

    Returns a list (not a view) so a concurrent reload can't raise
    ``RuntimeError: dictionary changed size during iteration`` in the caller's loop.
    """
    return list(PRODUCTS.values())


def iter_product_items() -> list[tuple[str, Product]]:
    """Snapshot of every (product_id, Product) pair. Snapshot rationale: see iter_products."""
    return list(PRODUCTS.items())


def _assert_no_slice_cache_conflicts(products: dict[str, Product]) -> None:
    """Reject a product set where one L1 cache entry would need two settings.

    The L1 slice cache is keyed on ``(source_path, sorted(variables))`` and
    ``ocean_masked`` is deliberately *not* in the key — it is applied before the
    result is cached, on the assumption that one store plus one variable set
    resolves to a single masking decision. Two products that share that identity
    but disagree would poison each other's cached slices, silently, in whichever
    order they were first requested.

    Fan-out alone cannot create this: a store/variable pair yields one product
    id. It takes a duplicate config specification or a metadata identity error —
    which is exactly why it fails loudly here rather than being assumed away.

    The sort is correct and load-bearing, not an oversight: a reversed pair
    genuinely shares an L1 entry (consumers read the cached Dataset by name, so
    channel order comes from ``product.variables``, never from the cached
    object). Unsorting this key would let a reversed pair with different masking
    slip past and poison the cache for real.
    """
    by_identity: dict[tuple[str, tuple[str, ...]], Product] = {}
    for product in products.values():
        identity = (product.source_path, tuple(sorted(product.variables)))
        existing = by_identity.get(identity)
        if existing is None:
            by_identity[identity] = product
            continue
        if existing.ocean_masked != product.ocean_masked:
            raise ValueError(
                f"Products {existing.id!r} and {product.id!r} share the slice-cache "
                f"identity {identity} but disagree on ocean_masked "
                f"({existing.ocean_masked} vs {product.ocean_masked}); one cached "
                "slice cannot satisfy both."
            )


def publish_products(new_products: dict[str, Product]) -> None:
    """Replace the registered product set with a fully verified one.

    Called once by tiler warmup, after discovery and store verification. Every
    product here has already been checked against its opened store, so this
    function neither validates nor opens anything — it only swaps state.

    Updates PRODUCTS in place without ever exposing an empty state to concurrent
    readers: additions/updates are applied first, then removals. A reader that
    races a publish sees either the previous set, the new set, or a transient
    with stale entries still present — never an empty dict.
    """
    if not new_products:
        raise ValueError(
            "Refusing to publish an empty product set; the tiler would serve an "
            "empty catalogue as though it were correct."
        )
    _assert_no_slice_cache_conflicts(new_products)

    for product_id, product in new_products.items():
        PRODUCTS[product_id] = product
    for stale_id in [k for k in PRODUCTS if k not in new_products]:
        del PRODUCTS[stale_id]
    logger.info(f"Published {len(PRODUCTS)} products")
