name: Test
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/environment/**"
permissions:
  id-token: write
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pre-commit-and-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
      - name: Configure Poetry to use Conda env
        shell: bash -el {0}
        run: |
          poetry config virtualenvs.create false
      - name: Install dependencies
        shell: bash -el {0}
        run: poetry install --no-root
      - name: Run pre-commit checks
        shell: bash -el {0}
        run: poetry run pre-commit run --all-files
      - name: Run tests
        shell: bash -el {0}
        run: |
          if [ -z "$(find . -name 'test_*.py')" ]; then echo "No tests found"; else export PROFILE=testing && poetry run pytest; fi
